### PR TITLE
Added Maven support and improved Makefile

### PR DESCRIPTION
**Pull request by dekobon**
This PR contains the changes needed to break the Java source into multiple Maven modules that can be built as artifacts deployable to Maven Central. There are minor source changes:

* Adding a new abstract class NativeBlockHasher.
* Adding dependency [Native Lib Loader](https://github.com/scijava/native-lib-loader).
* Improved Makefile to allow it to generate binaries and install them into the Java resource directory.
* Added JAR with dependencies to benchmark module so it can be a self-contained executable.
* Added compiled binaries for Linux x64 and Darwin x64.

### CODE REVIEW

**Comment by nayuki** [comment]
Thank you for the proposal, explanatory comments, and granular commits with appropriate log messages. Sorry, I cannot accept this patch because I'm unfamiliar with Maven, and the scope of the changes are significant.

**Comment by dekobon** [comment]
No problem. I dropped you a bomb of a change and there isn't a good way to make small incremental changes when moving to Maven. I'm doing my best to keep my branch current: https://github.com/dekobon/Native-hashes-for-Java

**Comment by nayuki** [comment]
Thanks for the reply. By the way, if you are continuing to merge with upstream, does this mean you are making use of this library in an application project?

**Comment by dekobon** [comment]
I've been merging the changes because I'm still evaluating native approaches to hashing with Java. I'm comparing your library against libnss andFastMd5.

I honestly think your library has a lot of promise, but it does need to be modified a bit to fit in with the common tools and patterns that many java developers use.

**Comment by dekobon** [comment]
My apologies for not directly answering in the above comment. I'm not using the library in a production application.

**Pull request closed without merging**
